from fastapi import APIRouter, HTTPException, Query
from typing import List, Dict, Any, Optional
from app.database.database import get_all_incidents, get_incident_by_id

router = APIRouter(prefix="/incidents", tags=["Incident Management"])

@router.get("")
def list_incidents(
    attack_type: Optional[str] = Query(None),
    risk_level: Optional[str] = Query(None),
    limit: int = Query(50, ge=1, le=200)
) -> List[Dict[str, Any]]:
    return get_all_incidents(limit=limit, attack_type=attack_type, risk_level=risk_level)

@router.get("/{incident_id}")
def get_incident(incident_id: str) -> Dict[str, Any]:
    inc = get_incident_by_id(incident_id)
    if not inc:
        raise HTTPException(status_code=404, detail="Incident record not found")
    return inc

@router.get("/{incident_id}/report")
def generate_incident_report(incident_id: str) -> Dict[str, Any]:
    inc = get_incident_by_id(incident_id)
    if not inc:
        raise HTTPException(status_code=404, detail="Incident record not found")
        
    pqc_ctrl = "ACTIVE (ML-KEM-768 / ML-DSA-65)"
    qrng_ctrl = "ACTIVE (Hadamard Superposition)" if inc['security_controls'].get('qrng_enabled') else "STANDBY"
    qkd_ctrl = "SIMULATED (BB84 Protocol)" if inc['security_controls'].get('qkd_enabled') else "STANDBY"
    
    text_report = f"""
================================================================================
                     Q-SHIELD SECURITY INCIDENT REPORT
================================================================================
Incident ID:          {inc['id']}
Event ID:             {inc['event_id']}
Timestamp (UTC):      {inc['timestamp']}
Simulation Type:      {inc['attack_type']}
Source Agent:         {inc['source_agent']} -> Destination Agent: {inc['destination_agent']}

RISK EVALUATION:
--------------------------------------------------------------------------------
Composite Risk Score: {inc['risk_score']} / 100
Assigned Risk Level:  {inc['risk_level']}
ML Risk Probability:  {inc['ml_prediction'].get('ml_risk_probability', 0.0) * 100:.1f}%

TRIGGERED AGENTS:
--------------------------------------------------------------------------------
{chr(10).join(f"  [+] {agent}" for agent in inc['triggered_agents'])}

MULTI-AGENT EVIDENCE TELEMETRY:
--------------------------------------------------------------------------------
{chr(10).join(f"  * {item.get('factor', 'Anomaly')}: {item.get('observed_value', '')} (+{item.get('score_addition', 0):.0f} pts)" for item in inc['evidence'])}

ADAPTIVE SECURITY POLICY & CONTROLS:
--------------------------------------------------------------------------------
  * Post-Quantum Cryptography (PQC): {pqc_ctrl}
  * Quantum Random Generator (QRNG):  {qrng_ctrl}
  * Quantum Key Distribution (QKD):   {qkd_ctrl}
  * Enhanced Zero-Trust Auth:         {"ENABLED" if inc['security_controls'].get('enhanced_authentication') else "DISABLED"}
  * Agent Channel Restriction:        {"ENFORCED" if inc['security_controls'].get('communication_restrictions') else "STANDARD"}

EXPLAINABLE DECISION RATIONALE:
--------------------------------------------------------------------------------
{inc['final_decision']}

RECOMMENDED MITIGATION ACTIONS:
--------------------------------------------------------------------------------
{inc['recommendation']}
================================================================================
Generated by Q-Shield Adaptive Multi-Agent Cyber-Risk & Post-Quantum Framework
================================================================================
"""
    return {
        "incident_id": inc['id'],
        "formatted_text_report": text_report.strip(),
        "incident_details": inc
    }
